on: push
jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: victorlin-resume.tex
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: victorlin-resume.pdf
